default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/rails_url_shortener_development.sqlite3

test:
  <<: *default
  database: db/rails_url_shortener_test.sqlite3

production:
  <<: *default
  database: db/rails_url_shortener_production.sqlite3
